services:
  ## Routers
  nosql-router-01:
    image: ${MONGO_IMAGE}
    container_name: nosql-router-01
    restart: always
    ports:
      - ${ROUTER_01_PORT}:27017
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_router_01_db:/data/db
      - nosql_mongodb_router_01_config:/data/configdb
    command: mongos --configdb rs-config-server/nosql-config-01:27017,nosql-config-02:27017,nosql-config-03:27017 --port 27017 --bind_ip_all --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  nosql-router-02:
    image: ${MONGO_IMAGE}
    container_name: nosql-router-02
    restart: always
    ports:
      - ${ROUTER_02_PORT}:27017
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_router_02_db:/data/db
      - nosql_mongodb_router_02_config:/data/configdb
    command: mongos --configdb rs-config-server/nosql-config-01:27017,nosql-config-02:27017,nosql-config-03:27017 --port 27017 --bind_ip_all --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  ## Config Servers
  nosql-config-01:
    image: ${MONGO_IMAGE}
    container_name: nosql-config-01
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_config_svr_01_db:/data/db
      - nosql_mongodb_config_svr_01_config:/data/configdb
    command: mongod --configsvr --replSet rs-config-server --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  nosql-config-02:
    image: ${MONGO_IMAGE}
    container_name: nosql-config-02
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_config_svr_02_db:/data/db
      - nosql_mongodb_config_svr_02_config:/data/configdb
    command: mongod --configsvr --replSet rs-config-server --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  nosql-config-03:
    image: ${MONGO_IMAGE}
    container_name: nosql-config-03
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_config_svr_03_db:/data/db
      - nosql_mongodb_config_svr_03_config:/data/configdb
    command: mongod --configsvr --replSet rs-config-server --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  ## Shard 1
  nosql-shard-01-node-01:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-01-node-01
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_01_node_01_db:/data/db
      - nosql_mongodb_shard_01_node_01_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-01 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  nosql-shard-01-node-02:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-01-node-02
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_01_node_02_db:/data/db
      - nosql_mongodb_shard_01_node_02_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-01 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  nosql-shard-01-node-03:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-01-node-03
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_01_node_03_db:/data/db
      - nosql_mongodb_shard_01_node_03_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-01 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  ## Shard 2
  nosql-shard-02-node-01:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-02-node-01
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_02_node_01_db:/data/db
      - nosql_mongodb_shard_02_node_01_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-02 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  nosql-shard-02-node-02:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-02-node-02
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_02_node_02_db:/data/db
      - nosql_mongodb_shard_02_node_02_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-02 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  nosql-shard-02-node-03:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-02-node-03
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_02_node_03_db:/data/db
      - nosql_mongodb_shard_02_node_03_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-02 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  ## Shard 3
  nosql-shard-03-node-01:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-03-node-01
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_03_node_01_db:/data/db
      - nosql_mongodb_shard_03_node_01_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-03 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    env_file: .env
    networks:
      - bridge_network

  nosql-shard-03-node-02:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-03-node-02
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_03_node_02_db:/data/db
      - nosql_mongodb_shard_03_node_02_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-03 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

  nosql-shard-03-node-03:
    image: ${MONGO_IMAGE}
    container_name: nosql-shard-03-node-03
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./keyfile:/etc/mongo-keyfile
      - nosql_mongodb_shard_03_node_03_db:/data/db
      - nosql_mongodb_shard_03_node_03_config:/data/configdb
    command: mongod --shardsvr --replSet rs-shard-03 --port 27017 --keyFile /etc/mongo-keyfile/keyfile
    networks:
      - bridge_network

volumes:
  nosql_mongodb_router_01_db:
  nosql_mongodb_router_01_config:
  nosql_mongodb_router_02_db:
  nosql_mongodb_router_02_config:
  nosql_mongodb_config_svr_01_db:
  nosql_mongodb_config_svr_01_config:
  nosql_mongodb_config_svr_02_db:
  nosql_mongodb_config_svr_02_config:
  nosql_mongodb_config_svr_03_db:
  nosql_mongodb_config_svr_03_config:
  nosql_mongodb_shard_01_node_01_db:
  nosql_mongodb_shard_01_node_01_config:
  nosql_mongodb_shard_01_node_02_db:
  nosql_mongodb_shard_01_node_02_config:
  nosql_mongodb_shard_01_node_03_db:
  nosql_mongodb_shard_01_node_03_config:
  nosql_mongodb_shard_02_node_01_db:
  nosql_mongodb_shard_02_node_01_config:
  nosql_mongodb_shard_02_node_02_db:
  nosql_mongodb_shard_02_node_02_config:
  nosql_mongodb_shard_02_node_03_db:
  nosql_mongodb_shard_02_node_03_config:
  nosql_mongodb_shard_03_node_01_db:
  nosql_mongodb_shard_03_node_01_config:
  nosql_mongodb_shard_03_node_02_db:
  nosql_mongodb_shard_03_node_02_config:
  nosql_mongodb_shard_03_node_03_db:
  nosql_mongodb_shard_03_node_03_config:

networks:
  bridge_network:
    driver: bridge
    name: ${BRIDGE_NETWORK_NAME}
