version: '3.8'

services:
  configsvr1:
    image: mongo:6.0
    container_name: configsvr1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - configsvr1_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard1-node1:
    image: mongo:6.0
    container_name: shard1-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard1_node1_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard1-node2:
    image: mongo:6.0
    container_name: shard1-node2
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard1_node2_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard1-node3:
    image: mongo:6.0
    container_name: shard1-node3
    command: ["mongod", "--shardsvr", "--replSet", "shard1", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard1_node3_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard2-node1:
    image: mongo:6.0
    container_name: shard2-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard2_node1_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard2-node2:
    image: mongo:6.0
    container_name: shard2-node2
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard2_node2_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  shard2-node3:
    image: mongo:6.0
    container_name: shard2-node3
    command: ["mongod", "--shardsvr", "--replSet", "shard2", "--port", "27018", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    volumes:
      - shard2_node3_data:/data/db
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

  mongos:
    image: mongo:6.0
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr1:27019", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/keyfile"]
    depends_on:
      - configsvr1
      - shard1-node1
      - shard1-node2
      - shard1-node3
      - shard2-node1
      - shard2-node2
      - shard2-node3
    ports:
      - "27017:27017"
    volumes:
      - ./keyfile:/etc/mongo-keyfile
    networks:
      - mongo-cluster

volumes:
  configsvr1_data:
  shard1_node1_data:
  shard1_node2_data:
  shard1_node3_data:
  shard2_node1_data:
  shard2_node2_data:
  shard2_node3_data:

networks:
  mongo-cluster:
